language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - "REDIS_PATCH=true"
  - "REDIS_PATCH=false"

install:
  - "if [ $REDIS_PATCH == true ]; then pip install redis; fi"
  - "python setup.py install"

script: "python test.py"

notifications:
  email: false
